
defaultPitchNames = ["C",  # default pitch names for pitch class
                     "C#",
                     "D",
                     "Eb",
                     "E",
                     "F",
                     "F#",
                     "G",
                     "Ab",
                     "A",
                     "Bb",
                     "B"]

chordTypes = {"0":          [0],             # one note
              # two note reductions:
              "5":          [0, 7],          # power chord
              "maj(omit5)": [0, 4],          # power chord
              "min(omit5)": [0, 3],          # power chord
              "d5":         [0, 6],          # diminished fifth
              # triads
              "maj":        [0, 4, 7],
              "min":        [0, 3, 7],
              "aug":        [0, 4, 7],
              "dim":        [0, 4, 7],
              "sus4":       [0, 4, 5],
              "sus2":       [0, 2, 7],
              # tetrads
              "7":          [0, 4, 7, 10],
              "maj7":       [0, 4, 7, 11],
              "min7":       [0, 3, 7, 10],
              "min(maj7)":  [0, 3, 7, 11],
              "min7(b5)":   [0, 3, 6, 10],
              "dim7":       [0, 3, 6, 9],
              }

"""
midiPitchMap = {"C-1": 0,
               "C#-1": 1,
               "D-1": 2,
               "Eb-1": 3,
               "E-1": 4,
               "F-1": 5,
               "F#-1": 6,
               "G-1": 7,
               "Ab-1": 8,
               "A-1": 9,
               "Bb-1": 10,
               "B-1": 11,
               "C0": 12,
               "C#0": 13,
               "D0": 14,
               "Eb0": 15,
               "E0": 16,
               "F0": 17,
               "F#0": 18,
               "G0": 19,
               "Ab0": 20,
                "A0": 21,
                "Bb0": 22,
                "B0": 23,
                "C1": 24,
                "C#1": 25,
                "D1": 26,
                "Eb1": 27,
                "E1": 28,
                "F1": 29,
                "F#1": 30,
                "G1": 31,
                "Ab1": 32,
                "A1": 33,
                "Bb1": 34,
                "B1": 35,
                "C2": 36,
                "C#2": 37,
                "D2": 38,
                "Eb2": 39,
                "E2": 40,
                "F2": 41,
                "F#2": 42,
                "G2": 43,
                "Ab2": 44,
                "A2": 45,
                "Bb2": 46,
                "B2": 47,
                "C3": 48,
                "C#3": 49,
                "D3": 50,
                "Eb3": 51,
                "E3": 52,
                "F3": 53,
                "F#3": 54,
                "G3": 55,
                "Ab3": 56,
                "A3": 57,
                "Bb3": 58,
                "B3": 59,
                "C4": 60,
                "C#4": 61,
                "D4": 62,
                "Eb4": 63,
                "E4": 64,
                "F4": 65,
                "F#4": 66,
                "G4": 67,
                "Ab4": 68,
                "A4": 69,
                "Bb4": 70,
                "B4": 71,
                "C5": 72,
                "C#5": 73,
                "D5": 74,
                "Eb5": 75,
                "E5": 76,
                "F5": 77,
                "F#5": 78,
                "G5": 79,
                "Ab5": 80,
                "A5": 81,
                "Bb5": 82,
                "B5": 83,
                "C6": 84,
                "C#6": 85,
                "D6": 86,
                "Eb6": 87,
                "E6": 88,
                "F6": 89,
                "F#6": 90,
                "G6": 91,
                "Ab6": 92,
                "A6": 93,
                "Bb6": 94,
                "B6": 95,
                "C7": 96,
                "C#7": 97,
                "D7": 98,
                "Eb7": 99,
                "E7": 100,
                "F7": 101,
                "F#7": 102,
                "G7": 103,
                "Ab7": 104,
                "A7": 105,
                "Bb7": 106,
                "B7": 107,
                "C8": 108,
                "C#8": 109,
                "D8": 110,
                "Eb8": 111,
                "E8": 112,
                "F8": 113,
                "F#8": 114,
                "G8": 115,
                "Ab8": 116,
                "A8": 117,
                "Bb8": 118,
                "B8": 119,
                "C9": 120,
                "C#9": 121,
                "D9": 122,
                "Eb9": 123,
                "E9": 124,
                "F9": 125,
                "F#9": 126,
                "G9": 127
                }
"""

generalMidiMap = {"Acoustic Bass Drum":35, #  from General Midi Specification
                  "Bass Drum 1":36,
                  "Side Stick":37,
                  "Acoustic Snare":38,
                  "Hand Clap":39,
                  "Electric Snare":40,
                  "Low Floor Tom":41,
                  "Closed Hi Hat":42,
                  "High Floor Tom":43,
                  "Pedal Hi-Hat":44,
                  "Low Tom":45,
                  "Open Hi-Hat":46,
                  "Low-Mid Tom":47,
                  "Hi-Mid Tom":48,
                  "Crash Cymbal 1":49,
                  "High Tom":50,
                  "Ride Cymbal 1":51,
                  "Chinese Cymbal":52,
                  "Ride Bell":53,
                  "Tambourine":54,
                  "Splash Cymbal":55,
                  "Cowbell":56,
                  "Crash Cymbal 2":57,
                  "Vibraslap":58,
                  "Ride Cymbal 2":59,
                  "Hi Bongo":60,
                  "Low Bongo":61,
                  "Mute Hi Conga":62,
                  "Open Hi Conga":63,
                  "Low Conga":64,
                  "High Timbale":65,
                  "Low Timbale":66,
                  "High Agogo":67,
                  "Low Agogo":68,
                  "Cabasa":69,
                  "Maracas":70,
                  "Short Whistle":71,
                  "Long Whistle":72,
                  "Short Guiro":73,
                  "Long Guiro":74,
                  "Claves":75,
                  "Hi Wood Block":76,
                  "Low Wood Block":77,
                  "Mute Cuica":78,
                  "Open Cuica":79,
                  "Mute Triangle":80,
                  "Open Triangle":81
                  }
